/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nipun sandaruwan
 */
public class DeleteAdminDetails extends javax.swing.JFrame {

    /**
     * Creates new form DeleteUserDetails
     */
    public DeleteAdminDetails() throws SQLException {
        initComponents();
        connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
 //TO CONNECT THE DATABASE   
    public void connect() throws SQLException
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
/////////////////////////////////////////////////////////////   
    
    public void LoadDataToTextfields()
    {
        String srch=SearchField2.getText();
        
       try {
            pst=con.prepareStatement("SELECT * FROM userdetails WHERE userid ='"+srch+"'" );
            rs=pst.executeQuery();
            
            if(rs.next())
            {
            FullNameTxt1.setText(rs.getString("Fullname"));
            AddressTxt1.setText(rs.getString("Address"));
            contactTxt1.setText(rs.getString("phoneNo"));
            AgeTxt1.setText(rs.getString("age"));
            Username2.setText(rs.getString("username"));
            PasswordTxt2.setText(rs.getString("password"));
/////////////////////////////////////////////////////////////////////////////////////////// 
 /////// To set the valus of the radio buttons according to the database values////////////
            String gender=(rs.getString("Gender"));
            if(gender.equals("Male")){
                
                    maleRBtn2.setSelected(true);
                    
         
            }else{
                    femaleRBtn2.setSelected(true);
                
            }
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    
    }
/////////////////////////////////////////////////////////   
    public void DeleteUserDataFromDB()
    {
        String tno=SearchField2.getText();
        
        try {
            pst=con.prepareStatement("DELETE FROM userdetails WHERE userid=?");
            pst.setString(1, tno);
            
            int k=pst.executeUpdate();
            
            if(k==1){
                JOptionPane.showMessageDialog(null,"Record Deleted!!");
            }
            else{
                JOptionPane.showMessageDialog(null,"Record Deletion failed!!");
            }
            FullNameTxt1.setText("");
            AddressTxt1.setText("");
            contactTxt1.setText("");
            AgeTxt1.setText("");
            Username2.setText("");
            SearchField2.setText(" ");
            PasswordTxt2.setText(" ");
            maleRBtn2.setSelected(true);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        SearchField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FullNameTxt1 = new javax.swing.JTextField();
        contactTxt1 = new javax.swing.JTextField();
        AgeTxt1 = new javax.swing.JTextField();
        Username2 = new javax.swing.JTextField();
        PasswordTxt2 = new javax.swing.JPasswordField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTxt1 = new javax.swing.JTextArea();
        femaleRBtn2 = new javax.swing.JRadioButton();
        maleRBtn2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Search User ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchField2.setBackground(new java.awt.Color(51, 204, 255));
        SearchField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchField2KeyReleased(evt);
            }
        });
        jPanel2.add(SearchField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 374, 42));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 410, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Delete Admin User");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 610, -1, -1));

        FullNameTxt1.setBackground(new java.awt.Color(0, 0, 0));
        FullNameTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullNameTxt1.setForeground(new java.awt.Color(255, 255, 255));
        FullNameTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jPanel1.add(FullNameTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 580, 40));

        contactTxt1.setBackground(new java.awt.Color(0, 0, 0));
        contactTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactTxt1.setForeground(new java.awt.Color(255, 255, 255));
        contactTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jPanel1.add(contactTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 330, 40));

        AgeTxt1.setBackground(new java.awt.Color(0, 0, 0));
        AgeTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeTxt1.setForeground(new java.awt.Color(255, 255, 255));
        AgeTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jPanel1.add(AgeTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, 330, 40));

        Username2.setBackground(new java.awt.Color(0, 0, 0));
        Username2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username2.setForeground(new java.awt.Color(255, 255, 255));
        Username2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 255, 255), 2, true));
        jPanel1.add(Username2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 600, 330, 40));

        PasswordTxt2.setBackground(new java.awt.Color(0, 0, 0));
        PasswordTxt2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordTxt2.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 2, true));
        jPanel1.add(PasswordTxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 670, 330, 40));

        AddressTxt1.setBackground(new java.awt.Color(0, 0, 0));
        AddressTxt1.setColumns(20);
        AddressTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddressTxt1.setForeground(new java.awt.Color(255, 255, 255));
        AddressTxt1.setRows(5);
        AddressTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 2, true));
        jScrollPane1.setViewportView(AddressTxt1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 580, 120));

        femaleRBtn2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(femaleRBtn2);
        femaleRBtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        femaleRBtn2.setForeground(new java.awt.Color(255, 255, 255));
        femaleRBtn2.setText("Female");
        femaleRBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(femaleRBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 530, -1, -1));

        maleRBtn2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(maleRBtn2);
        maleRBtn2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maleRBtn2.setForeground(new java.awt.Color(255, 255, 255));
        maleRBtn2.setText("Male");
        maleRBtn2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(maleRBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Reset");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 2, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 740, 170, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Delete");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 255, 255), 2, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 740, 170, 60));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 680, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1118, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 826, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
            FullNameTxt1.setText("");
            AddressTxt1.setText("");
            contactTxt1.setText("");
            AgeTxt1.setText("");
            Username2.setText("");
            SearchField2.setText(" ");
            PasswordTxt2.setText(" ");
            maleRBtn2.setSelected(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DeleteUserDataFromDB();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void SearchField2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchField2KeyReleased
        // TODO add your handling code here:
        LoadDataToTextfields();
    }//GEN-LAST:event_SearchField2KeyReleased

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            PasswordTxt2.setEchoChar((char)0);
        }else{
            PasswordTxt2.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteAdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteAdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteAdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteAdminDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DeleteAdminDetails().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DeleteAdminDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTxt1;
    private javax.swing.JTextField AgeTxt1;
    private javax.swing.JTextField FullNameTxt1;
    private javax.swing.JPasswordField PasswordTxt2;
    private javax.swing.JTextField SearchField2;
    private javax.swing.JTextField Username2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contactTxt1;
    private javax.swing.JRadioButton femaleRBtn2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton maleRBtn2;
    // End of variables declaration//GEN-END:variables
}
