/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Nipun sandaruwan
 */
public class EditAdminUserDetails extends javax.swing.JFrame {

    /**
     * Creates new form EditUserDetails
     */
    public EditAdminUserDetails() throws SQLException {
        initComponents();
        connect();
    }
    
    Connection con;
    PreparedStatement pst;
    ResultSet rs;
    
 //TO CONNECT THE DATABASE   
    public void connect() throws SQLException
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection("jdbc:mysql://localhost:3306/test","root","");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AddTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }
    
/////////////////////////////////////////////////////////////   
    
    public void GetDataFromDB()
    {
        String srch=jTextField1.getText();
        
        try {
            pst=con.prepareStatement("SELECT * FROM userdetails WHERE userid ='"+srch+"'" );
            rs=pst.executeQuery();
            
            if(rs.next())
            {
            FullNameTxt.setText(rs.getString("Fullname"));
            AddressTxt.setText(rs.getString("Address"));
            contactTxt.setText(rs.getString("phoneNo"));
            AgeTxt.setText(rs.getString("age"));
            Username1.setText(rs.getString("username"));
            PasswordTxt1.setText(rs.getString("password"));
/////////////////////////////////////////////////////////////////////////////////////////// 
 /////// To set the valus of the radio buttons according to the database values////////////
            String gender=(rs.getString("Gender"));
            if(gender.equals("Male")){
                
                    maleRBtn1.setSelected(true);
                    
         
            }else{
                    femaleRBtn1.setSelected(true);
                
            }
            }
        } catch (Exception e) {
            
            e.printStackTrace();
        }
    
    }
/////////////////////////////////////////////////////////   
    public void EditUserDataInDb()
    {
        String srch=jTextField1.getText();
        String fname=FullNameTxt.getText();
        String Addres=AddressTxt.getText();
        String contac=contactTxt.getText();
        String Ag=AgeTxt.getText();
        String uname=Username1.getText();
        String pward=PasswordTxt1.getText();
        String gender = null;
             if(maleRBtn1.isSelected()){
                      gender = "Male";
         
            }else if (femaleRBtn1.isSelected()){
                      gender = "Female";
                    }
        
        try {
           pst=con.prepareStatement("UPDATE userdetails SET Fullname=?,Address=?,phoneNo=?,age=?,Gender=?,username=?,password=? WHERE userid =?");
            
            pst.setString(1, fname);
            pst.setString(2, Addres);
            pst.setString(3, contac);
            pst.setString(4, Ag);
            pst.setString(5, gender);
            pst.setString(6, uname);
            pst.setString(7, pward);
            pst.setString(8, srch);
            
            int k=pst.executeUpdate();
            
            if(k==1){
                JOptionPane.showMessageDialog(null,"Record Edited sucessfully!");
                
            }
            else{
                JOptionPane.showMessageDialog(null,"Record Edit process failed!!");
            }
            
                FullNameTxt.setText("");
                AddressTxt.setText("");
                contactTxt.setText("");
                AgeTxt.setText("");
                Username1.setText("");
                PasswordTxt1.setText("");
                maleRBtn1.setSelected(true);
                jTextField1.setText(" ");
            
            
            
        } catch (SQLException ex) {
            Logger.getLogger(AddTrain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FullNameTxt = new javax.swing.JTextField();
        contactTxt = new javax.swing.JTextField();
        AgeTxt = new javax.swing.JTextField();
        Username1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AddressTxt = new javax.swing.JTextArea();
        maleRBtn1 = new javax.swing.JRadioButton();
        femaleRBtn1 = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        PasswordTxt1 = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();

        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true), "Search User ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jTextField1.setBackground(new java.awt.Color(0, 204, 255));
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 414, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 450, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Edit Admin user Details");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 680, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Adderss");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Contact No");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Age");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Username");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 600, -1, -1));

        FullNameTxt.setBackground(new java.awt.Color(0, 0, 0));
        FullNameTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        FullNameTxt.setForeground(new java.awt.Color(255, 255, 255));
        FullNameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(FullNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 760, 40));

        contactTxt.setBackground(new java.awt.Color(0, 0, 0));
        contactTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        contactTxt.setForeground(new java.awt.Color(255, 255, 255));
        contactTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(contactTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 380, 370, 50));

        AgeTxt.setBackground(new java.awt.Color(0, 0, 0));
        AgeTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgeTxt.setForeground(new java.awt.Color(255, 255, 255));
        AgeTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(AgeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 370, 50));

        Username1.setBackground(new java.awt.Color(0, 0, 0));
        Username1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Username1.setForeground(new java.awt.Color(255, 255, 255));
        Username1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(Username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 590, 370, 50));

        AddressTxt.setBackground(new java.awt.Color(0, 0, 0));
        AddressTxt.setColumns(20);
        AddressTxt.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AddressTxt.setForeground(new java.awt.Color(255, 255, 255));
        AddressTxt.setRows(5);
        AddressTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jScrollPane1.setViewportView(AddressTxt);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 760, -1));

        maleRBtn1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(maleRBtn1);
        maleRBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        maleRBtn1.setForeground(new java.awt.Color(255, 255, 255));
        maleRBtn1.setText("Male");
        jPanel1.add(maleRBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, -1, -1));

        femaleRBtn1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(femaleRBtn1);
        femaleRBtn1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        femaleRBtn1.setForeground(new java.awt.Color(255, 255, 255));
        femaleRBtn1.setText("Female");
        jPanel1.add(femaleRBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 530, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Reset");
        jButton3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 760, 140, 60));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Edit");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 760, 140, 60));

        PasswordTxt1.setBackground(new java.awt.Color(0, 0, 0));
        PasswordTxt1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        PasswordTxt1.setForeground(new java.awt.Color(255, 255, 255));
        PasswordTxt1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 255), 2, true));
        jPanel1.add(PasswordTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 670, 370, 50));

        jCheckBox1.setBackground(new java.awt.Color(0, 0, 0));
        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 255, 255));
        jCheckBox1.setText("Show password");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 680, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1049, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
        GetDataFromDB();
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        EditUserDataInDb();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
                FullNameTxt.setText("");
                AddressTxt.setText("");
                contactTxt.setText("");
                AgeTxt.setText("");
                Username1.setText("");
                PasswordTxt1.setText("");
                maleRBtn1.setSelected(true);
                jTextField1.setText(" ");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if(jCheckBox1.isSelected()){
            PasswordTxt1.setEchoChar((char)0);
        }else{
            PasswordTxt1.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditAdminUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditAdminUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditAdminUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditAdminUserDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EditAdminUserDetails().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EditAdminUserDetails.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AddressTxt;
    private javax.swing.JTextField AgeTxt;
    private javax.swing.JTextField FullNameTxt;
    private javax.swing.JPasswordField PasswordTxt1;
    private javax.swing.JTextField Username1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField contactTxt;
    private javax.swing.JRadioButton femaleRBtn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton maleRBtn1;
    // End of variables declaration//GEN-END:variables
}
